# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof/PhysX/externals/cmakemodules/GetCompilerAndPlatform.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof/PhysX/externals/cmakemodules/NvidiaBuildOptions.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof/PhysX/externals/cmakemodules/SetOutputPaths.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof/PhysX/physx/snippets/compiler/cmake/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof/PhysX/physx/snippets/compiler/cmake/SnippetRender.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof/PhysX/physx/snippets/compiler/cmake/SnippetTemplate.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof/PhysX/physx/snippets/compiler/cmake/SnippetUtils.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof/PhysX/physx/snippets/compiler/cmake/SnippetVehicleTemplate.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof/PhysX/physx/snippets/compiler/cmake/mac/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof/PhysX/physx/snippets/compiler/cmake/mac/SnippetRender.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof/PhysX/physx/snippets/compiler/cmake/mac/SnippetTemplate.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof/PhysX/physx/snippets/compiler/cmake/mac/SnippetUtils.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/adriand/Documents/Dev/Vulkan/Floof/PhysX/physx/snippets/compiler/cmake/mac/SnippetVehicleTemplate.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/FindGLUT.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/FindOpenGL.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/FindPkgConfig.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /opt/homebrew/Cellar/cmake/3.24.2/share/cmake/Modules/SelectLibraryConfigurations.cmake))

/Users/adriand/Documents/Dev/Vulkan/Floof/PhysX/physx/compiler/mac64/CMakeFiles/cmake.check_cache: $(TARGETS)
	/opt/homebrew/Cellar/cmake/3.24.2/bin/cmake -H/Users/adriand/Documents/Dev/Vulkan/Floof/PhysX/physx/compiler/public -B/Users/adriand/Documents/Dev/Vulkan/Floof/PhysX/physx/compiler/mac64
